s/_Doze/Doze/
s/_DozeAsmCall/DozeAsmCall/
s/_DozeAsmRead/DozeAsmRead/
s/_DozeAsmRun/DozeAsmRun/
s/_DozeIn/DozeIn/
s/_DozeMemFetch/DozeMemFetch/
s/_DozeMemRead/DozeMemRead/
s/_DozeMemWrite/DozeMemWrite/
s/_DozeOut/DozeOut/
s/_DozeRead/DozeRead/
s/_DozeWrite/DozeWrite/
s/_nDozeCycles/nDozeCycles/
s/_nDozeEi/nDozeEi/
